---
- name: install java
  yum: name=java state=installed

- name: create jenkins.repo
  template:
    src: jenkins.repo.j2
    dest: /etc/yum.repos.d/jenkins.repo
    owner: root
    group: root
    mode: 0644

- name: import verification key
  command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install jenkins
  yum: name=jenkins state=installed

- name: Start jenkins
  systemd: state=started name=jenkins
